version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
