package io.kindx.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.kindx.constants.Language;
import io.kindx.entity.converter.LanguageSetConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

import static io.kindx.entity.Location.TABLE_NAME;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = TABLE_NAME)
public class Location {
    public static final String TABLE_NAME = "locations";
    public static final String LOCATION_ID_ATTR_NAME = "location_id";

    @DynamoDBHashKey(attributeName = LOCATION_ID_ATTR_NAME)
    @DynamoDBAutoGeneratedKey
    private String locationId;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "lat")
    private Double lat;

    @DynamoDBAttribute(attributeName = "long")
    private Double lon;

    @DynamoDBAttribute(attributeName = "search_radius")
    private Integer searchRadius;

    @DynamoDBAttribute(attributeName = "radius_reduction_factor")
    private Integer radiusReductionFactor;

    @DynamoDBAttribute(attributeName = "is_disabled")
    private Boolean isDisabled;

    @DynamoDBAttribute(attributeName = "default_languages")
    @DynamoDBTypeConverted(converter = LanguageSetConverter.class)
    private Set<Language> defaultLanguages;

    @DynamoDBAttribute(attributeName = "created_timestamp")
    private Long createdTimestamp;
}
