package io.kindx.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import static io.kindx.entity.PlacesCacheEntry.TABLE_NAME;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = TABLE_NAME)
public class PlacesCacheEntry {

    public static final String TABLE_NAME = "google_places_cache";
    public static final String PLACES_ID_ATTR_NAME = "places_id";


    @DynamoDBHashKey(attributeName = PLACES_ID_ATTR_NAME)
    @DynamoDBAutoGeneratedKey
    private String placesId;

    @DynamoDBAttribute(attributeName = "details")
    private String details;

    @DynamoDBAttribute(attributeName = "created_timestamp")
    private Long createdTimestamp;
}
