package io.kindx.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import io.kindx.backoffice.processor.notification.NotificationChannel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

import static io.kindx.entity.User.TABLE_NAME;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@DynamoDBTable(tableName = TABLE_NAME)
public class User {

    public static final String TABLE_NAME = "users";
    public static final String USER_ID_ATTR_NAME = "user_id";


    @DynamoDBHashKey(attributeName = USER_ID_ATTR_NAME)
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute(attributeName = "locale")
    private String locale;

    @DynamoDBAttribute(attributeName = "is_disabled")
    private Boolean isDisabled;

    @DynamoDBAttribute(attributeName = "general_food_preferences")
    private Set<String> generalFoodPreferences;

    @DynamoDBAttribute(attributeName = "last_activity_timestamp")
    private Long lastActivityTimestamp;

    @DynamoDBAttribute(attributeName = "created_timestamp")
    private Long createdTimestamp;

    @DynamoDBAttribute(attributeName = "notification_channel_id")
    private String notificationChannelId;

    @DynamoDBTypeConvertedEnum
    @DynamoDBAttribute(attributeName = "notification_channel")
    private NotificationChannel notificationChannel;

    @DynamoDBVersionAttribute
    private Long version;


}
